vehicles/tatacars/urls.py
from django.conf.urls.static import static
from django.urls import path, include

from vehicles import settings
from .import views
from .views import add_car

app_name='tatacars'
urlpatterns = [

    path('',views.car,name='car'),
    path('car/<int:car_id>/',views.detail,name='detail'),
    path('add_car',views.add_car,name='add_car'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete<int:id>/hel',views.delete,name='delete')
]


if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

vehicles/vehicles/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("tatacars.urls"))
]

vehicles/tatacars/models.py
from django.db import models

# Create your models here.
class Car(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

vehicles/tatacars/forms.py
from django import forms
from .models import Car

class CarForm(forms.ModelForm):
    class Meta:
        model=Car
        fields=['name','desc','year','img']

vehicles/tatacars/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Car
from .forms import CarForm


def car(request):
    car=Car.objects.all()
    context={
        'car_list':car
    }
    return render(request,'car.html',context)

def detail(request,car_id):
    car=Car.objects.get(id=car_id)
    return render(request,'detail.html', {'car':car})
def add_car(request):
    if request.method=="POST":
        name=request.POST.get('name',)
        desc = request.POST.get('desc', )
        year = request.POST.get('year', )
        img = request.FILES['img']
        car=Car(name=name,desc=desc,year=year,img=img)
        car.save()
    return render(request,'add.html')
def update(request,id):
    car=Car.objects.get(id=id)
    form=CarForm(request.POST or None,request.FILES,instance=car)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'car':car})

def delete(request,id):
    if request.method== 'POST':
        car=Car.objects.get(id=id)
        car.delete()
        return redirect('/')
    return render(request,'delete.html')





# Create your views here.

vehicles/templates/add.html
{% extends 'base.html'%}
{% block body %}

<form method="post" enctype="multipart/form-data">

  {% csrf_token %}

  <input type="text" name="name" placeholder="Enter the car name"><br>
  <input type="text" name="desc" placeholder="Enter the car description"><br>
  <input type="text" name="year" placeholder="Enter the car year of production"><br>
  <input type="file" name="img">

  <input type="submit">
</form>

{% endblock %}

vehicles/templates/base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>

<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
      TATA MOTORS<br>
      CONNECTING ASPIRATIONS
  </a>
</nav>

{% block body %}
{% endblock %}
</body>
</html>

vehicles/templates/car.html
{% extends 'base.html'%}
{% block body %}
<div class="container">
    <div class="row">
        {% for i in car_list %}
      <div class="col-md-4">
<div class="card" style="width: 300px;margin-top:10px">

  <img src="{{i.img.url}}" class="card-img-top" alt="..." width="250px" height="250px">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.desc}}</p>
    <a href="{% url 'tatacars:detail' i.id %}" class="btn btn-primary">Select</a>
  </div>
</div>

</div>

{% endfor %}
    </div>

<a class="btn btn-primary"href="{% url 'tatacars:add_car' %}">add_car</a><br>

</div>






{% endblock %}

vehicles/templates/delete.html
<form method="POST">
    {% csrf_token %}
    Are sure to delete the item?
    <input type="submit">
</form>

vehicles/templates/detail.html
{% extends 'base.html'%}
{% block body %}
<div class="container">
    <div class="row">
     <div class="col-md-4">
        <img src="{{car.img.url}}" width="300" height="300">
     </div>
        <div class="col-md-6">
  <h6>{{car.name}}</h6>
 <h4> {{car.desc}}</h4>
 <h6> {{car.year}}</h6>
  <a class="btn btn-warning"href="{%url 'tatacars:update' car.id%}">update</a>
  <a class="btn btn-danger"href="{%url 'tatacars:delete' car.id%}">delete</a>
 </div>



   </div>

</div>

{% endblock %}

vehicles/templates/edit.html
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}

  <input type="submit">

</form>